### ISSUE TITLE
Multiple InputFormatters supported?

### ISSUE THREAD

**Issue by slthomason** [kashifsoofi/DotNetSandbox#1]
Great article!

So I need to be able to accept both raw strings for certain scenarios, as well as application/json. Once I added this code, then any of my POSTs where I try to post json that it before would deserialize for me now I get errors like:

An unhandled exception has occurred while executing the request
System.InvalidCastException: Unable to cast object of type ‘System.String’ to type <T>.

When I comment out the addition in the Startup.cs, then my json POSTs work again. How do I get it to accept both?

**Comment by kashifsoofi** [comment]
Its been a while so I would have to look what can be the cause of it but my wild guess would be to try setting the json serialisation setting to ignore null values.

**Comment by slthomason** [comment]
I just found a solution and issues a pull request.  :)  Thanks again for the article!
